// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using French.Erp.ViewModel.Interface;

#nullable disable

namespace French.Erp.Application.ViewModel
{
    public partial class CidadeViewModel : IViewModel
    {
        public CidadeViewModel()
        {
            Cliente = new HashSet<ClienteViewModel>();
        }

        /// <summary>
        /// Codigo
        /// </summary>
        public int CidadeId { get; set; }
        /// <summary>
        /// Nome
        /// </summary>
        public string Nome { get; set; }
        public short EstadoId { get; set; }

        [JsonIgnore]
        public virtual EstadoViewModel Estado { get; set; }
        [JsonIgnore]
        public virtual ICollection<ClienteViewModel> Cliente { get; set; }
    }
}