// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using French.Erp.ViewModel.Interface;
using System;
using System.Collections.Generic;

#nullable disable

namespace French.Erp.Application.ViewModel
{
    public partial class EstadoViewModel : IViewModel
    {
        public EstadoViewModel()
        {
            Cidade = new HashSet<CidadeViewModel>();
        }

        public short EstadoId { get; set; }
        /// <summary>
        /// UF
        /// </summary>
        public string SiglaUf { get; set; }
        /// <summary>
        /// Descricao
        /// </summary>
        public string NomeUf { get; set; }

        public virtual ICollection<CidadeViewModel> Cidade { get; set; }
    }
}