// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using French.Erp.ViewModel.Interface;
using System;
using System.Collections.Generic;

#nullable disable

namespace French.Erp.Application.ViewModel
{
    public partial class TarefaItemViewModel : IViewModel
    {
        public int TarefaItemId { get; set; }
        public int TarefaId { get; set; }
        public byte Ordem { get; set; }
        public string Descricao { get; set; }
        public int ServicoId { get; set; }
        public DateTime? Data { get; set; }
        public decimal HorasOrcadas { get; set; }
        public decimal HorasGastas { get; set; }
        public decimal ValorHora { get; set; }
        public decimal ValorItem { get; set; }

        public virtual ServicoViewModel Servico { get; set; }
        public virtual TarefaViewModel Tarefa { get; set; }
    }
}