// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using French.Erp.ViewModel.Interface;

#nullable disable

namespace French.Erp.Application.ViewModel
{
    public partial class TipoDePessoaViewModel: IViewModel
    {
        public TipoDePessoaViewModel()
        {
            Cliente = new HashSet<ClienteViewModel>();
        }

        public byte TipoDePessoaId { get; set; }
        public string Descricao { get; set; }

        public virtual ICollection<ClienteViewModel> Cliente { get; set; }
    }
}