// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using French.Erp.ViewModel.Interface;
using System;
using System.Collections.Generic;

#nullable disable

namespace French.Erp.Application.ViewModel
{
    public partial class TributoViewModel: IViewModel
    {
        public TributoViewModel()
        {
            TributoNotaFiscal = new HashSet<TributoNotaFiscalViewModel>();
        }

        /// <summary>
        /// Codigo
        /// </summary>
        public int TributoId { get; set; }
        /// <summary>
        /// Descricao
        /// </summary>
        public string Descricao { get; set; }
        /// <summary>
        /// Valor
        /// </summary>
        public decimal Percentual { get; set; }
        public bool RetemNaNota { get; set; }
        public decimal FaixaInicial { get; set; }
        public decimal FaixaFinal { get; set; }
        public decimal ValorDeducao { get; set; }

        public virtual ICollection<TributoNotaFiscalViewModel> TributoNotaFiscal { get; set; }
    }
}