// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;
using System.Collections.Generic;
using Validation = Dietcode.Core.DomainValidator;

#nullable disable

namespace French.Erp.Domain.Entities
{
    [Table("ArquivoNotaFiscal")]
    public partial class ArquivoNotaFiscal
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ArquivoNotaFiscalId { get; set; }

        public int NotaFiscalId { get; set; }

        [Required]
        public byte[] Arquivo { get; set; }

        [ForeignKey("NotaFiscalId")]
        [InverseProperty("ArquivoNotaFiscals")]
        public virtual NotaFiscal NotaFiscal { get; set; }
    }
}

