// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace French.Erp.Domain.Entities
{
    public partial class Cidade
    {
        public Cidade()
        {
            Cliente = new HashSet<Cliente>();
        }

        /// <summary>
        /// Codigo
        /// </summary>
        public int CidadeId { get; set; }
        /// <summary>
        /// Nome
        /// </summary>
        public string Nome { get; set; }
        public int EstadoId { get; set; }

        public virtual Estado Estado { get; set; }
        public virtual ICollection<Cliente> Cliente { get; set; }
    }
}