// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Validation = Dietcode.Core.DomainValidator;

#nullable disable

namespace French.Erp.Domain.Entities
{
    [Table("Cidade")]
    public partial class Cidade
    {
        public Cidade()
        {
            Cliente = new HashSet<Cliente>();
        }

        /// <summary>
        /// Codigo
        /// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CidadeId { get; set; }
        /// <summary>
        /// Nome
        /// </summary>
        public string Nome { get; set; }
        public int EstadoId { get; set; }

        public virtual Estado Estado { get; set; }

        [JsonIgnore]
        public virtual ICollection<Cliente> Cliente { get; set; }
    }
}