// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Validation = Dietcode.Core.DomainValidator;
using French.Erp.Domain.Validations;
using System.Text.Json.Serialization;

#nullable disable

namespace French.Erp.Domain.Entities
{

    [Table("Cidade")]
    public partial class Cidade
    {
        public Cidade()
        {
            Clientes = new List<Cliente>();
        }
        /// <summary>
        /// Codigo
        /// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CidadeId { get; set; }

        [Required]
        [StringLength(100)]
        public string Nome { get; set; }

        public int EstadoId { get; set; }

        [JsonIgnore]
        [InverseProperty("Cidade")]
        public virtual IList<Cliente> Clientes { get; set; } = new List<Cliente>();

        [ForeignKey("EstadoId")]
        [InverseProperty("Cidades")]
        public virtual Estado Estado { get; set; }
    }
}