// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Validation = Dietcode.Core.DomainValidator;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using French.Erp.Domain.Validations;

#nullable disable

namespace French.Erp.Domain.Entities
{
    [Table("Cliente")]
    public partial class Cliente
    {
        private readonly Validation.ValidationResult validationResult;
        private bool? isValid;

        public Cliente()
        {
            validationResult = new Validation.ValidationResult();
            isValid = null;
            Faturamentos = new List<Faturamento>();
            NotaFiscals = new List<NotaFiscal>();
            Tarefas = new List<Tarefa>();
        }

        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ClienteId { get; set; }

        [Required]
        [MaxLength(50)]
        public string Nome { get; set; }

        [Required]
        [MaxLength(100)]
        public string RazaoSocial { get; set; }

        [Required]
        [MaxLength(30)]
        public string Documento { get; set; }

        public byte TipoDeClienteId { get; set; }

        public byte TipoDePessoaId { get; set; }

        [MaxLength(50)]
        public string Telefone { get; set; }

        [MaxLength(50)]
        public string Contato { get; set; }

        [MaxLength(100)]
        public string Email { get; set; }

        [MaxLength(50)]
        public string InscricaoEstadual { get; set; }

        [MaxLength(50)]
        public string CadastroMunicipal { get; set; }

        [MaxLength(100)]
        public string Endereco { get; set; }

        [MaxLength(5)]
        public string Numero { get; set; }

        [MaxLength(20)]
        public string Complemento { get; set; }

        [MaxLength(50)]
        public string Bairro { get; set; }

        [MaxLength(20)]
        public string Cep { get; set; }

        public int? EstadoId { get; set; }

        public int? CidadeId { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime? DataAlteracao { get; set; }

        public int UsuarioId { get; set; }

        [ForeignKey("CidadeId")]
        [InverseProperty("Clientes")]
        public virtual Cidade Cidade { get; set; }

        [InverseProperty("Cliente")]
        public virtual IList<Faturamento> Faturamentos { get; set; } = new List<Faturamento>();

        [InverseProperty("Cliente")]
        public virtual IList<NotaFiscal> NotaFiscals { get; set; } = new List<NotaFiscal>();

        [InverseProperty("Cliente")]
        public virtual IList<Tarefa> Tarefas { get; set; } = new List<Tarefa>();

        [ForeignKey("TipoDeClienteId")]
        [InverseProperty("Clientes")]
        public virtual TipoDeCliente TipoDeCliente { get; set; }

        [ForeignKey("TipoDePessoaId")]
        [InverseProperty("Clientes")]
        public virtual TipoDePessoa TipoDePessoa { get; set; }

        #region Dados de Validação
        public virtual Validation.ValidationResult ValidationResult => validationResult;

        public virtual bool IsValid()
        {
            if (!isValid.HasValue)
            {
                var validationDados = Validar();
                if (!validationDados.Valid)
                {
                    validationDados.Erros.ToList().ForEach(e => validationResult.Add(e));
                }
                return validationResult.Valid;
            }
            return isValid.Value;

        }

        public virtual Validation.ValidationResult Validar()
        {
            var entidadeNomeValidate = new ClienteEstaConsistente();
            var validationResultEntidade = entidadeNomeValidate.Validar(this);
            isValid = validationResultEntidade.Valid;
            if (!validationResultEntidade.Valid)
            {
                validationResultEntidade.Erros.ToList().ForEach(e => validationResult.Add(e));
            }

            return validationResult;
        }

        #endregion

    }
}