// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Validation = Dietcode.Core.DomainValidator;
using French.Erp.Domain.Validations.Clientes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace French.Erp.Domain.Entities
{
    [Table("Cliente")]
    public partial class Cliente
    {
        private readonly Validation.ValidationResult validationResult;
        private bool? isValid;

        public Cliente()
        {
            validationResult = new Validation.ValidationResult();
            isValid = null;
            Faturamento = new List<Faturamento>();
            NotaFiscal = new List<NotaFiscal>();
            Tarefa = new List<Tarefa>();
        }

        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ClienteId { get; set; }
        
        [Column, MaxLength(100)]
        public string Nome { get; set; }
        
        [Column, MaxLength(100)]
        public string RazaoSocial { get; set; }
        
        [Column, MaxLength(20)]
        public string Documento { get; set; }

        [Column]
        public byte TipoDeClienteId { get; set; }

        [Column]
        public byte TipoDePessoaId { get; set; }

        [Column, MaxLength(15)]
        public string Telefone { get; set; }

        [Column, MaxLength(50)]
        public string Contato { get; set; }

        [Column, MaxLength(100)]
        public string Email { get; set; }

        [Column, MaxLength(20)]
        public string InscricaoEstadual { get; set; }

        [Column, MaxLength(20)]
        public string CadastroMunicipal { get; set; }

        [Column, MaxLength(100)]
        public string Endereco { get; set; }

        [Column, MaxLength(5)]
        public string Numero { get; set; }

        [Column, MaxLength(20)]
        public string Complemento { get; set; }

        [Column, MaxLength(50)]
        public string Bairro { get; set; }

        [Column, MaxLength(10)]
        public string Cep { get; set; }

        [Column]
        public int UsuarioId { get; set; }

        [Column]
        public int? EstadoId { get; set; }

        [Column]
        public int? CidadeId { get; set; }

        [Column]
        public DateTime? DataCriacao { get; set; }

        [Column]
        public DateTime? DataAlteracao { get; set; }

        
        public virtual Cidade Cidade { get; set; }
        public virtual TipoDeCliente TipoDeCliente { get; set; }
        public virtual TipoDePessoa TipoDePessoa { get; set; }
        public virtual IList<Faturamento> Faturamento { get; set; }
        public virtual IList<NotaFiscal> NotaFiscal { get; set; }
        public virtual IList<Tarefa> Tarefa { get; set; }

        #region Dados de Validação
        public virtual Validation.ValidationResult ValidationResult => validationResult;

        public virtual bool IsValid()
        {
            if (!isValid.HasValue)
            {
                var validationDados = Validar();
                if (!validationDados.Valid)
                {
                    validationDados.Erros.ToList().ForEach(e => validationResult.Add(e));
                }
                return validationResult.Valid;
            }
            return isValid.Value;

        }

        public virtual Validation.ValidationResult Validar()
        {
            var entidadeNomeValidate = new ClienteEstaConsistente();
            var validationResultEntidade = entidadeNomeValidate.Validar(this);
            isValid = validationResultEntidade.Valid;
            if (!validationResultEntidade.Valid)
            {
                validationResultEntidade.Erros.ToList().ForEach(e => validationResult.Add(e));
            }

            return validationResult;
        }

        #endregion

    }
}