// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Validation = Dietcode.Core.DomainValidator;

#nullable disable

namespace French.Erp.Domain.Entities
{
    [Table("ComposicaoNotaFiscal")]
    public partial class ComposicaoNotaFiscal
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ComposicaoNotaFiscalId { get; set; }

        [Column, Required]
        public int NotaFiscalId { get; set; }

        [Column,Required]
        public int TarefaId { get; set; }

        [Column(TypeName = "numeric(18, 2)")]
        public decimal Total { get; set; }

        [ForeignKey("NotaFiscalId")]
        [InverseProperty("ComposicaoNotaFiscals")]
        public virtual NotaFiscal NotaFiscal { get; set; }

        [ForeignKey("TarefaId")]
        [InverseProperty("ComposicaoNotaFiscals")]
        public virtual Tarefa Tarefa { get; set; }
    }
}