// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace French.Erp.Domain.Entities
{
    public partial class Cor
    {
        /// <summary>
        /// Codigo
        /// </summary>
        public int CorId { get; set; }
        /// <summary>
        /// Descricao
        /// </summary>
        public string Nome { get; set; }
    }
}