// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using French.Erp.Domain.Validations;

namespace French.Erp.Domain.Entities
{
    public partial class Cor
    {
        /// <summary>
        /// Codigo
        /// </summary>
        public int CorId { get; set; }

        /// <summary>
        /// Descricao
        /// </summary>
        [Required]
        [MaxLength(50)]
        public string Nome { get; set; }
    }
}