// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using French.Erp.Domain.Validations.Clientes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace French.Erp.Domain.Entities
{
    [Table("Estado")]
    public class Estado
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int EstadoId { get; set; }
        [Column, MaxLength(2)]
        public string SiglaUf { get; set; }
        [Column, MaxLength(50)]
        public string NomeUf { get; set; }

        public virtual IList<Cidade> Cidade { get; set; }
    }
}