// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace French.Erp.Domain.Entities
{
    public partial class Estado
    {
        public Estado()
        {
            Cidade = new HashSet<Cidade>();
        }

        public int EstadoId { get; set; }
        /// <summary>
        /// UF
        /// </summary>
        public string SiglaUf { get; set; }
        /// <summary>
        /// Descricao
        /// </summary>
        public string NomeUf { get; set; }

        public virtual ICollection<Cidade> Cidade { get; set; }
    }
}