// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Dietcode.Core.DomainValidator;
using French.Erp.Domain.Validations.Clientes;
using System;
using System.Collections.Generic;
using System.Linq;

#nullable disable

namespace French.Erp.Domain.Entities
{
    public partial class Faturamento
    {
        private readonly ValidationResult validationResult;
        private bool? isValid;

        public Faturamento()
        {
            validationResult = new ValidationResult();
            isValid = null;
        }

        public int FaturamentoId { get; set; }
        public int ClienteId { get; set; }
        public short Ano { get; set; }
        public byte Mes { get; set; }
        public decimal Valor { get; set; }
        public bool Faturado { get; set; }
        public int UsuarioId { get; set; }

        public virtual Cliente Cliente { get; set; }


        #region Dados de Validação
        public virtual ValidationResult ValidationResult => validationResult;

        public virtual bool IsValid()
        {
            if (!isValid.HasValue)
            {
                var validationDados = Validar();
                if (!validationDados.Valid)
                {
                    validationDados.Erros.ToList().ForEach(e => validationResult.Add(e));
                }
                return validationResult.Valid;
            }
            return isValid.Value;

        }

        public virtual ValidationResult Validar()
        {
            //var entidadeNomeValidate = new ClienteEstaConsistente();
            //var validationResultEntidade = entidadeNomeValidate.Validar(this);
            //isValid = validationResultEntidade.Valid;
            //if (!validationResultEntidade.Valid)
            //{
            //    validationResultEntidade.Erros.ToList().ForEach(e => validationResult.Add(e));
            //}

            return validationResult;
        }

        #endregion

    }
}