// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Validation = Dietcode.Core.DomainValidator;
using French.Erp.Domain.Validations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace French.Erp.Domain.Entities
{
    [Table("Faturamento")]
    public partial class Faturamento : EntityBase<Faturamento>
    {
        public Faturamento()
        {
        }

        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity), Required]
        public int FaturamentoId { get; set; }
        [Column, Required]
        public int ClienteId { get; set; }
        [Column, Required]
        public short Ano { get; set; }
        [Column, Required]
        public byte Mes { get; set; }
        [Column, Required]
        public decimal Valor { get; set; }
        [Column, Required]
        public bool Faturado { get; set; }
        [Column, Required]
        public int UsuarioId { get; set; }

        [ForeignKey("ClienteId")]
        [InverseProperty("Faturamentos")]
        public virtual Cliente Cliente { get; set; }


        #region Dados de Validação
        protected override Validation.Validator<Faturamento> ObterValidador()
        {
            return null; //new ClienteEstaConsistente();
        }

        #endregion

    }
}