// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace French.Erp.Domain.Entities
{
    public partial class Mes
    {
        /// <summary>
        /// Numero
        /// </summary>
        public byte MesId { get; set; }

        /// <summary>
        /// Nome
        /// </summary>
        [Required,MaxLength(15)]

        public string Nome { get; set; }
    }
}