// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Validation = Dietcode.Core.DomainValidator;

#nullable disable

namespace French.Erp.Domain.Entities
{
    [Table("NotaFiscal")]
    public partial class NotaFiscal
    {
        public NotaFiscal()
        {
            ArquivoNotaFiscals = new List<ArquivoNotaFiscal>();
            ComposicaoNotaFiscals = new List<ComposicaoNotaFiscal>();
            TributoNotaFiscals = new List<TributoNotaFiscal>();
        }

        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int NotaFiscalId { get; set; }

        [Required, Column, MaxLength(10)]
        public string Numero { get; set; }

        public int ClienteId { get; set; }

        [Required, Column, MaxLength(100)]
        public string CodigoVerificacao { get; set; }

        [Column(TypeName = "DateTime")]
        public DateTime Data { get; set; }

        [Column(TypeName = "numeric(18, 2)")]
        public decimal Valor { get; set; }

        [Column(TypeName = "numeric(18, 2)")]
        public decimal ImpostoTotalRetido { get; set; }

        [Column(TypeName = "numeric(18, 2)")]
        public decimal ValorLiquido { get; set; }

        [Column, MaxLength(50)]
        public string Descricao { get; set; }

        [Column]
        public byte StatusNotaFiscalId { get; set; }

        [Column]
        public int UsuarioId { get; set; }

        [InverseProperty("NotaFiscal")]
        public virtual IList<ArquivoNotaFiscal> ArquivoNotaFiscals { get; set; } = new List<ArquivoNotaFiscal>();

        [ForeignKey("ClienteId")]
        [InverseProperty("NotaFiscals")]
        public virtual Cliente Cliente { get; set; }

        [InverseProperty("NotaFiscal")]
        public virtual IList<ComposicaoNotaFiscal> ComposicaoNotaFiscals { get; set; } = new List<ComposicaoNotaFiscal>();

        [ForeignKey("StatusNotaFiscalId")]
        [InverseProperty("NotaFiscals")]
        public virtual StatusNotaFiscal StatusNotaFiscal { get; set; }

        [InverseProperty("NotaFiscal")]
        public virtual IList<TributoNotaFiscal> TributoNotaFiscals { get; set; } = new List<TributoNotaFiscal>();
    }
}