// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using French.Erp.ViewModel.Interface;
using System;
using System.Collections.Generic;

#nullable disable

namespace French.Erp.Application.ViewModel
{
    public partial class CorDto: IViewModel
    {
        /// <summary>
        /// Codigo
        /// </summary>
        public int CorId { get; set; }
        /// <summary>
        /// Descricao
        /// </summary>
        public string Nome { get; set; }
    }
}