// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using French.Erp.ViewModel.Interface;
using System;
using System.Collections.Generic;

#nullable disable

namespace French.Erp.Application.ViewModel
{
    public partial class MesDto
    {
        /// <summary>
        /// Numero
        /// </summary>
        public byte MesId { get; set; }
        /// <summary>
        /// Nome
        /// </summary>
        public string Nome { get; set; }
    }
}