// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using French.Erp.ViewModel.Interface;

#nullable disable

namespace French.Erp.Application.ViewModel
{
    public partial class ServicoDto : IViewModel
    {
        public ServicoDto()
        {
            TarefaItem = new HashSet<TarefaItemDto>();
        }

        public int ServicoId { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }

        public virtual ICollection<TarefaItemDto> TarefaItem { get; set; }
    }
}